In [1]:
import pandas as pd
import yaml



try:
    with open("../cfg.yaml", "r") as file:
        cfg=yaml.safe_load(file)
except:
    print("Yaml configuration file not found!")

In [2]:
renew=pd.read_csv(cfg['output_data']['df1'])

In [3]:
renew.head()

       country  year prct_access_elec   prct_renew_prod prct_renew_cons
0  Afghanistan  2015             71.5  2.83229014034404            17.7
1  Afghanistan  2016             97.7  3.19005850365957            20.2
2  Afghanistan  2017             97.7  3.16865225907967            19.5
3  Afghanistan  2018             93.4  3.47404347045087            18.3
4  Afghanistan  2019             97.7  3.82453122312059            18.9

In [4]:
display(renew.isna().sum())

country             0
year                0
prct_access_elec    0
prct_renew_prod     0
prct_renew_cons     0
dtype: int64

In [5]:
gdp_pop=pd.read_csv(cfg['output_data']['df2'])

In [6]:
gdp_pop.head()

       country  year           GDP  population  gdp_per_cap
0  Afghanistan  2014  1.950046e+10  32792523.0   594.661805
1  Afghanistan  2015  1.869957e+10  33831764.0   552.722397
2  Afghanistan  2016  1.822435e+10  34700612.0   525.188137
3  Afghanistan  2017  1.903430e+10  35688935.0   533.339054
4  Afghanistan  2018  1.885632e+10  36743039.0   513.194331

In [7]:
display(gdp_pop.shape)
display(renew.shape)

(2321, 5)

(2660, 5)

In [8]:
display(gdp_pop.dtypes)
display(renew.dtypes)

country            str
year             int64
GDP            float64
population     float64
gdp_per_cap    float64
dtype: object

country               str
year                int64
prct_access_elec      str
prct_renew_prod       str
prct_renew_cons       str
dtype: object

In [9]:
display(gdp_pop.country.value_counts())
display(renew.country.value_counts())

country
Afghanistan                           11
Albania                               11
Algeria                               11
Andorra                               11
Angola                                11
                                      ..
Venezuela (Bolivarian Republic of)    11
Viet Nam                              11
Yemen                                 11
Zambia                                11
Zimbabwe                              11
Name: count, Length: 211, dtype: int64

country
Afghanistan                    10
Africa Eastern and Southern    10
Africa Western and Central     10
Albania                        10
Algeria                        10
                               ..
West Bank and Gaza             10
World                          10
Yemen, Rep.                    10
Zambia                         10
Zimbabwe                       10
Name: count, Length: 266, dtype: int64

In [10]:
new=pd.read_csv('/Users/iirene/Desktop/renewables_new.csv')
new.head()

,Series Name,Series Code,Country Name,Country Code,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024]
0,Access to electricity (% of population),EG.ELC.ACCS.ZS,Afghanistan,AFG,89.5,71.5,97.7,97.7,93.4,97.7,97.7,97.7,85.3,85.3,..
1,Access to electricity (% of population),EG.ELC.ACCS.ZS,Albania,ALB,100,100,99.9,99.9,100,100,100,100,100,100,..
2,Access to electricity (% of population),EG.ELC.ACCS.ZS,Algeria,DZA,99.3,99.4,99.4,99.5,99.6,99.5,99.7,99.8,100,100,..
3,Access to electricity (% of population),EG.ELC.ACCS.ZS,American Samoa,ASM,..,..,..,..,..,..,..,..,..,..,..
4,Access to electricity (% of population),EG.ELC.ACCS.ZS,Andorra,AND,100,100,100,100,100,100,100,100,100,100,..

In [11]:
def clean_years(col):
    return col.split('[')[0].strip()

new.columns=[clean_years(col) for col in new.columns]
new.columns

Index(['Series Name', 'Series Code', 'Country Name', 'Country Code', '2014',
       '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023',
       '2024'],
      dtype='str')

In [12]:
def rename_column(col):
    return col.lower().replace(' ','_').strip()

new.columns=[rename_column(col) for col in new.columns]
new.columns

Index(['series_name', 'series_code', 'country_name', 'country_code', '2014',
       '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023',
       '2024'],
      dtype='str')

In [13]:
new=new.drop(columns=['series_code'])
new.columns

Index(['series_name', 'country_name', 'country_code', '2014', '2015', '2016',
       '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024'],
      dtype='str')

In [14]:
display(new.duplicated().sum())
display(new.duplicated())

np.int64(2)

0      False
1      False
2      False
3      False
4      False
       ...
880    False
881     True
882     True
883    False
884    False
Length: 885, dtype: bool

In [15]:
new.loc[[881,882]]

,series_name,country_name,country_code,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
881,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
new = new.drop(index=[881,882])
new.duplicated().sum()

np.int64(0)

In [17]:
display(new.isna().sum())
display(new.loc[new.isna().any(axis=1)])

series_name     1
country_name    3
country_code    3
2014            3
2015            3
2016            3
2017            3
2018            3
2019            3
2020            3
2021            3
2022            3
2023            3
2024            3
dtype: int64

,series_name,country_name,country_code,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
880,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
883,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
884,Last Updated: 04/08/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
new=new.dropna()
display(new.isna().sum())

series_name     0
country_name    0
country_code    0
2014            0
2015            0
2016            0
2017            0
2018            0
2019            0
2020            0
2021            0
2022            0
2023            0
2024            0
dtype: int64

In [19]:
new.dtypes

series_name     str
country_name    str
country_code    str
2014            str
2015            str
2016            str
2017            str
2018            str
2019            str
2020            str
2021            str
2022            str
2023            str
2024            str
dtype: object

In [20]:
years=['2014','2015','2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024']
new_melt = pd.melt(new, id_vars=['country_name', 'country_code','series_name'], value_vars=years, var_name='year', value_name='value')
display(new_melt.head())

,country_name,country_code,series_name,year,value
0,Afghanistan,AFG,Access to electricity (% of population),2014,89.5
1,Albania,ALB,Access to electricity (% of population),2014,100
2,Algeria,DZA,Access to electricity (% of population),2014,99.3
3,American Samoa,ASM,Access to electricity (% of population),2014,..
4,Andorra,AND,Access to electricity (% of population),2014,100

In [21]:
new_df=new_melt.pivot(index=['country_name','country_code','year'],columns='series_name',values='value').reset_index()
new_df.head()

series_name,country_name,country_code,year,Access to electricity (% of population),"Electricity production from renewable sources, excluding hydroelectric (% of total)","Electricity production from renewable sources, excluding hydroelectric (kWh)",Renewable energy consumption (% of total final energy consumption)
0,Afghanistan,AFG,2014,89.5,2.77200987806233,32440000,19.1
1,Afghanistan,AFG,2015,71.5,2.83229014034404,33440000,17.7
2,Afghanistan,AFG,2016,97.7,3.19005850365957,38660000,20.2
3,Afghanistan,AFG,2017,97.7,3.16865225907967,39470000,19.5
4,Afghanistan,AFG,2018,93.4,3.47404347045087,38680000,18.3

In [22]:
map_new={'country_name':'country','Access to electricity (% of population)':'prct_access_elec','Electricity production from renewable sources, excluding hydroelectric (kWh)':'renew_prod_kwh','Electricity production from renewable sources, excluding hydroelectric (% of total)':'prct_renew_prod','Renewable energy consumption (% of total final energy consumption)':'prct_renew_cons'}
new_df=new_df.rename(columns=map_new)
new_df.columns

Index(['country', 'country_code', 'year', 'prct_access_elec',
       'prct_renew_prod', 'renew_prod_kwh', 'prct_renew_cons'],
      dtype='str', name='series_name')

In [23]:
new_df.dtypes

series_name
country             str
country_code        str
year                str
prct_access_elec    str
prct_renew_prod     str
renew_prod_kwh      str
prct_renew_cons     str
dtype: object

In [24]:
new_df.year.value_counts()

year
2014    220
2015    220
2016    220
2017    220
2018    220
2019    220
2020    220
2021    220
2022    220
2023    220
2024    220
Name: count, dtype: int64

In [25]:
new_df['year']=new_df['year'].astype(int)

In [26]:
new_df['prct_access_elec']=new_df['prct_access_elec'].astype(float)

ValueError: could not convert string to float: '..'

In [27]:
new_df["prct_access_elec"] = (new_df["prct_access_elec"].replace("..", pd.NA).astype(float))
new_df['prct_access_elec']=new_df['prct_access_elec'].astype(float)
display(new_df["prct_access_elec"].isna().sum())
display(new_df.loc[new_df["prct_access_elec"].isna()])

np.int64(240)

series_name,country,country_code,year,prct_access_elec,prct_renew_prod,renew_prod_kwh,prct_renew_cons
10,Afghanistan,AFG,2024,NaN,..,..,..
21,Africa Eastern and Southern,AFE,2024,NaN,..,..,..
32,Africa Western and Central,AFW,2024,NaN,..,..,..
43,Albania,ALB,2024,NaN,..,..,..
54,Algeria,DZA,2024,NaN,..,..,..
...,...,...,...,...,...,...,...
2375,Virgin Islands (U.S.),VIR,2024,NaN,..,..,..
2386,West Bank and Gaza,PSE,2024,NaN,..,..,..
2397,"Yemen, Rep.",YEM,2024,NaN,..,..,..
2408,Zambia,ZMB,2024,NaN,..,..,..
2419,Zimbabwe,ZWE,2024,NaN,..,..,..

In [28]:
new_df['prct_renew_prod'] = (new_df['prct_renew_prod'].replace('..', pd.NA).astype(float))
new_df['prct_renew_prod']=new_df['prct_renew_prod'].astype(float)
display(new_df['prct_renew_prod'].isna().sum())
display(new_df.loc[new_df['prct_renew_prod'].isna()])

np.int64(730)

series_name,country,country_code,year,prct_access_elec,prct_renew_prod,renew_prod_kwh,prct_renew_cons
8,Afghanistan,AFG,2022,85.300000,NaN,..,20
9,Afghanistan,AFG,2023,85.300000,NaN,..,..
10,Afghanistan,AFG,2024,NaN,NaN,..,..
19,Africa Eastern and Southern,AFE,2022,48.801258,NaN,..,..
20,Africa Eastern and Southern,AFE,2023,50.667516,NaN,..,..
...,...,...,...,...,...,...,...
2407,Zambia,ZMB,2023,51.100000,NaN,..,..
2408,Zambia,ZMB,2024,NaN,NaN,..,..
2417,Zimbabwe,ZWE,2022,50.100000,NaN,..,..
2418,Zimbabwe,ZWE,2023,62.000000,NaN,..,..
2419,Zimbabwe,ZWE,2024,NaN,NaN,..,..

In [29]:
new_df['renew_prod_kwh'] = (new_df['renew_prod_kwh'].replace('..', pd.NA).astype(float))
new_df['renew_prod_kwh']=new_df['renew_prod_kwh'].astype(float)
display(new_df['renew_prod_kwh'].isna().sum())
display(new_df.loc[new_df['renew_prod_kwh'].isna()])

np.int64(730)

series_name,country,country_code,year,prct_access_elec,prct_renew_prod,renew_prod_kwh,prct_renew_cons
8,Afghanistan,AFG,2022,85.300000,NaN,NaN,20
9,Afghanistan,AFG,2023,85.300000,NaN,NaN,..
10,Afghanistan,AFG,2024,NaN,NaN,NaN,..
19,Africa Eastern and Southern,AFE,2022,48.801258,NaN,NaN,..
20,Africa Eastern and Southern,AFE,2023,50.667516,NaN,NaN,..
...,...,...,...,...,...,...,...
2407,Zambia,ZMB,2023,51.100000,NaN,NaN,..
2408,Zambia,ZMB,2024,NaN,NaN,NaN,..
2417,Zimbabwe,ZWE,2022,50.100000,NaN,NaN,..
2418,Zimbabwe,ZWE,2023,62.000000,NaN,NaN,..
2419,Zimbabwe,ZWE,2024,NaN,NaN,NaN,..

In [30]:
new_df['prct_renew_cons'] = (new_df['prct_renew_cons'].replace('..', pd.NA).astype(float))
new_df['prct_renew_cons']=new_df['prct_renew_cons'].astype(float)
display(new_df['prct_renew_cons'].isna().sum())
display(new_df.loc[new_df['prct_renew_cons'].isna()])

np.int64(632)

series_name,country,country_code,year,prct_access_elec,prct_renew_prod,renew_prod_kwh,prct_renew_cons
9,Afghanistan,AFG,2023,85.300000,NaN,NaN,NaN
10,Afghanistan,AFG,2024,NaN,NaN,NaN,NaN
18,Africa Eastern and Southern,AFE,2021,48.127211,5.300963,2.083713e+10,NaN
19,Africa Eastern and Southern,AFE,2022,48.801258,NaN,NaN,NaN
20,Africa Eastern and Southern,AFE,2023,50.667516,NaN,NaN,NaN
...,...,...,...,...,...,...,...
2407,Zambia,ZMB,2023,51.100000,NaN,NaN,NaN
2408,Zambia,ZMB,2024,NaN,NaN,NaN,NaN
2417,Zimbabwe,ZWE,2022,50.100000,NaN,NaN,NaN
2418,Zimbabwe,ZWE,2023,62.000000,NaN,NaN,NaN
2419,Zimbabwe,ZWE,2024,NaN,NaN,NaN,NaN

In [31]:
display(new_df.shape)
display(new_df.isna().sum())

(2420, 7)

series_name
country               0
country_code          0
year                  0
prct_access_elec    240
prct_renew_prod     730
renew_prod_kwh      730
prct_renew_cons     632
dtype: int64

In [32]:
display(new_df.loc[new_df.isna().any(axis=1)])

series_name,country,country_code,year,prct_access_elec,prct_renew_prod,renew_prod_kwh,prct_renew_cons
8,Afghanistan,AFG,2022,85.300000,NaN,NaN,20.0
9,Afghanistan,AFG,2023,85.300000,NaN,NaN,NaN
10,Afghanistan,AFG,2024,NaN,NaN,NaN,NaN
18,Africa Eastern and Southern,AFE,2021,48.127211,5.300963,2.083713e+10,NaN
19,Africa Eastern and Southern,AFE,2022,48.801258,NaN,NaN,NaN
...,...,...,...,...,...,...,...
2407,Zambia,ZMB,2023,51.100000,NaN,NaN,NaN
2408,Zambia,ZMB,2024,NaN,NaN,NaN,NaN
2417,Zimbabwe,ZWE,2022,50.100000,NaN,NaN,NaN
2418,Zimbabwe,ZWE,2023,62.000000,NaN,NaN,NaN
2419,Zimbabwe,ZWE,2024,NaN,NaN,NaN,NaN

In [33]:
new_df.country.value_counts()

country
Afghanistan                    11
Africa Eastern and Southern    11
Africa Western and Central     11
Albania                        11
Algeria                        11
                               ..
Virgin Islands (U.S.)          11
West Bank and Gaza             11
Yemen, Rep.                    11
Zambia                         11
Zimbabwe                       11
Name: count, Length: 220, dtype: int64

In [34]:
new_df = new_df.loc[~new_df["country"].isin(["Africa Eastern and Southern","Africa Western and Central","Arab World"])]

In [35]:
new_df.country.value_counts()

country
Afghanistan              11
Albania                  11
Algeria                  11
American Samoa           11
Andorra                  11
                         ..
Virgin Islands (U.S.)    11
West Bank and Gaza       11
Yemen, Rep.              11
Zambia                   11
Zimbabwe                 11
Name: count, Length: 217, dtype: int64

In [36]:
# Dropping years from 2021 to 2024 because of missing data about renewables production:
new_years = new_df.loc[~new_df['year'].isin([2021,2022,2023,2024])]

In [37]:
display(new_years.shape)
display(new_years.isna().sum())

(1519, 7)

series_name
country              0
country_code         0
year                 0
prct_access_elec    14
prct_renew_prod     61
renew_prod_kwh      61
prct_renew_cons     35
dtype: int64

In [38]:
display(new_years.loc[new_years.isna().any(axis=1)])

series_name,country,country_code,year,prct_access_elec,prct_renew_prod,renew_prod_kwh,prct_renew_cons
55,American Samoa,ASM,2014,NaN,1.502037,2360000.0,0.2
56,American Samoa,ASM,2015,NaN,1.519312,2490000.0,0.2
57,American Samoa,ASM,2016,NaN,1.831159,3130000.0,0.2
58,American Samoa,ASM,2017,NaN,4.587482,7740000.0,0.3
59,American Samoa,ASM,2018,NaN,4.756228,7980000.0,0.3
...,...,...,...,...,...,...,...
2048,St. Martin (French part),MAF,2016,100.0,1.408852,2970000.0,NaN
2049,St. Martin (French part),MAF,2017,100.0,0.097082,170000.0,NaN
2050,St. Martin (French part),MAF,2018,100.0,0.013629,20000.0,NaN
2051,St. Martin (French part),MAF,2019,100.0,0.267873,450000.0,NaN
2052,St. Martin (French part),MAF,2020,100.0,0.685087,1210000.0,NaN

In [39]:
new_years.isna().any(axis=1).sum()

np.int64(82)

In [40]:
missing_rows = new_years.loc[new_years.isna().any(axis=1)]
display(missing_rows)

series_name,country,country_code,year,prct_access_elec,prct_renew_prod,renew_prod_kwh,prct_renew_cons
55,American Samoa,ASM,2014,NaN,1.502037,2360000.0,0.2
56,American Samoa,ASM,2015,NaN,1.519312,2490000.0,0.2
57,American Samoa,ASM,2016,NaN,1.831159,3130000.0,0.2
58,American Samoa,ASM,2017,NaN,4.587482,7740000.0,0.3
59,American Samoa,ASM,2018,NaN,4.756228,7980000.0,0.3
...,...,...,...,...,...,...,...
2048,St. Martin (French part),MAF,2016,100.0,1.408852,2970000.0,NaN
2049,St. Martin (French part),MAF,2017,100.0,0.097082,170000.0,NaN
2050,St. Martin (French part),MAF,2018,100.0,0.013629,20000.0,NaN
2051,St. Martin (French part),MAF,2019,100.0,0.267873,450000.0,NaN
2052,St. Martin (French part),MAF,2020,100.0,0.685087,1210000.0,NaN

In [41]:
new_years.country.nunique()

217

In [42]:
# Cleaning country names using a doctionary basing on the difference of country names with the co2 dataset:
country_name_map = {
    "Bahamas, The": "Bahamas",
    "Brunei Darussalam": "Brunei",
    "Cabo Verde": "Cape Verde",
    "Congo, Dem. Rep.": "Democratic Republic of Congo",
    "Congo, Rep.": "Congo",
    "Egypt, Arab Rep.": "Egypt",
    "Gambia, The": "Gambia",
    "Hong Kong SAR, China": "Hong Kong",
    "Iran, Islamic Rep.": "Iran",
    "Korea, Dem. People's Rep.": "North Korea",
    "Korea, Rep.": "South Korea",
    "Kyrgyz Republic": "Kyrgyzstan",
    "Lao PDR": "Laos",
    "Macao SAR, China": "Macao",
    "Micronesia, Fed. Sts.": "Micronesia (country)",
    "Russian Federation": "Russia",
    "Slovak Republic": "Slovakia",
    "Somalia, Fed. Rep.": "Somalia",
    "St. Kitts and Nevis": "Saint Kitts and Nevis",
    "St. Lucia": "Saint Lucia",
    "St. Vincent and the Grenadines": "Saint Vincent and the Grenadines",
    "Syrian Arab Republic": "Syria",
    "Timor-Leste": "East Timor",
    "Turkiye": "Turkey",
    "Venezuela, RB": "Venezuela",
    "Viet Nam": "Vietnam",
    "West Bank and Gaza": "Palestine",
    "Yemen, Rep.": "Yemen"
}

new_years_clean = new_years.copy()

new_years_clean["country"] = new_years_clean["country"].replace(country_name_map)
new_years_clean.country.nunique()

217

In [43]:
energy_co2 = pd.read_csv("../data/clean/energy_co2_data_cleaned.csv")

energy_co2 = energy_co2.rename(columns={"iso_code": "country_code"})

In [44]:
new_years["year"] = new_years["year"].astype(int)
energy_co2["year"] = energy_co2["year"].astype(int)

new_years["country"] = new_years["country"].astype(str).str.strip()
energy_co2["country"] = energy_co2["country"].astype(str).str.strip()

new_years["country_code"] = new_years["country_code"].astype(str).str.strip()
energy_co2["country_code"] = energy_co2["country_code"].astype(str).str.strip()

In [45]:
energy_co2.isna().sum()

country             0
year                0
country_code       11
co2                 0
co2_luc           231
prim_ener_cons    236
region              0
dtype: int64

In [46]:
countries_co2 = energy_co2.loc[energy_co2.isna().any(axis=1),'country'].unique()
countries_co2

<StringArray>
[             'Afghanistan',                  'Albania',
                  'Andorra',                   'Angola',
                 'Anguilla',      'Antigua and Barbuda',
                  'Armenia',                    'Aruba',
                  'Bahamas',                  'Bahrain',
 ...
                  'Tunisia', 'Turks and Caicos Islands',
                   'Tuvalu',                   'Uganda',
                  'Uruguay',                  'Vanuatu',
        'Wallis and Futuna',                    'Yemen',
                   'Zambia',                 'Zimbabwe']
Length: 138, dtype: str

In [47]:
energy_co2.shape

(2365, 7)

In [48]:
new_years_clean.shape

(1519, 7)

In [57]:
# Doing the join on left on the new years dataset as we have already dropped the years (2022-24) for which we don't have data and therefore won't be relevant if there is data in the co2 dataset:
joint_df = new_years_clean.merge(energy_co2,on=["country", "year"],how="left")

In [58]:
joint_df.head()

,country,country_code_x,year,prct_access_elec,prct_renew_prod,renew_prod_kwh,prct_renew_cons,country_code_y,co2,co2_luc,prim_ener_cons,region
0,Afghanistan,AFG,2014,89.5,2.772010,32440000.0,19.1,AFG,8.697668,8.776041,26.630217,Asia
1,Afghanistan,AFG,2015,71.5,2.832290,33440000.0,17.7,AFG,9.384400,9.696866,30.953520,Asia
2,Afghanistan,AFG,2016,97.7,3.190059,38660000.0,20.2,AFG,8.605932,8.944815,28.075348,Asia
3,Afghanistan,AFG,2017,97.7,3.168652,39470000.0,19.5,AFG,9.311054,14.564168,36.517418,Asia
4,Afghanistan,AFG,2018,93.4,3.474043,38680000.0,18.3,AFG,10.191504,13.073680,46.492512,Asia

In [59]:
joint_df.shape

(1519, 12)

In [60]:
joint_df.isna().sum()

country               0
country_code_x        0
year                  0
prct_access_elec     14
prct_renew_prod      61
renew_prod_kwh       61
prct_renew_cons      35
country_code_y       91
co2                  84
co2_luc             175
prim_ener_cons      126
region               84
dtype: int64

In [61]:
display(joint_df.loc[joint_df['co2_luc'].isna()])

,country,country_code_x,year,prct_access_elec,prct_renew_prod,renew_prod_kwh,prct_renew_cons,country_code_y,co2,co2_luc,prim_ener_cons,region
21,American Samoa,ASM,2014,NaN,1.502037,2360000.0,0.2,NaN,NaN,NaN,NaN,NaN
22,American Samoa,ASM,2015,NaN,1.519312,2490000.0,0.2,NaN,NaN,NaN,NaN,NaN
23,American Samoa,ASM,2016,NaN,1.831159,3130000.0,0.2,NaN,NaN,NaN,NaN,NaN
24,American Samoa,ASM,2017,NaN,4.587482,7740000.0,0.3,NaN,NaN,NaN,NaN,NaN
25,American Samoa,ASM,2018,NaN,4.756228,7980000.0,0.3,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1486,Virgin Islands (U.S.),VIR,2016,100.0,1.977894,13600000.0,5.7,NaN,NaN,NaN,NaN,NaN
1487,Virgin Islands (U.S.),VIR,2017,100.0,1.434548,7510000.0,5.3,NaN,NaN,NaN,NaN,NaN
1488,Virgin Islands (U.S.),VIR,2018,100.0,2.416661,14760000.0,5.8,NaN,NaN,NaN,NaN,NaN
1489,Virgin Islands (U.S.),VIR,2019,100.0,2.381567,14760000.0,6.2,NaN,NaN,NaN,NaN,NaN
1490,Virgin Islands (U.S.),VIR,2020,100.0,2.272307,14760000.0,5.9,NaN,NaN,NaN,NaN,NaN

In [62]:
# dropping columns that are no longer useful to us:
joint_df = joint_df.drop(columns=["country_code_y","country_code_x"])
joint_df.columns

Index(['country', 'year', 'prct_access_elec', 'prct_renew_prod',
       'renew_prod_kwh', 'prct_renew_cons', 'co2', 'co2_luc', 'prim_ener_cons',
       'region'],
      dtype='str')

In [63]:
# Check which are the countries associated with missing values:
countries_missing = joint_df.loc[joint_df.isna().any(axis=1),'country'].unique()

display(countries_missing)

<StringArray>
[           'American Samoa',                   'Andorra',
                     'Aruba',                   'Bermuda',
    'British Virgin Islands',            'Cayman Islands',
           'Channel Islands',                   'Curacao',
             'Faroe Islands',          'French Polynesia',
                 'Gibraltar',                 'Greenland',
                      'Guam',                 'Hong Kong',
               'Isle of Man',                    'Kosovo',
             'Liechtenstein',                     'Macao',
          'Marshall Islands',                    'Monaco',
             'New Caledonia',  'Northern Mariana Islands',
                     'Palau',          'Puerto Rico (US)',
                'San Marino', 'Sint Maarten (Dutch part)',
  'St. Martin (French part)',  'Turks and Caicos Islands',
     'Virgin Islands (U.S.)']
Length: 29, dtype: str

In [64]:
# Dropping irrelevant countries with missing data because they are small territories with small scale or incomplete energy coverage:
countries_to_drop = [
    "American Samoa",
    "Andorra",
    "Aruba",
    "Bermuda",
    "British Virgin Islands",
    "Cayman Islands",
    "Channel Islands",
    "Curacao",
    "Faroe Islands",
    "French Polynesia",
    "Gibraltar",
    "Greenland",
    "Guam",
    "Hong Kong",
    "Isle of Man",
    "Kosovo",
    "Liechtenstein",
    "Macao",
    "Marshall Islands",
    "Monaco",
    "New Caledonia",
    "Northern Mariana Islands",
    "Palau",
    "Puerto Rico (US)",
    "San Marino",
    "Sint Maarten (Dutch part)",
    "St. Martin (French part)",
    "Turks and Caicos Islands",
    "Virgin Islands (U.S.)"]

energy_df = joint_df.loc[~joint_df["country"].isin(countries_to_drop)].copy()
energy_df.head()

,country,year,prct_access_elec,prct_renew_prod,renew_prod_kwh,prct_renew_cons,co2,co2_luc,prim_ener_cons,region
0,Afghanistan,2014,89.5,2.772010,32440000.0,19.1,8.697668,8.776041,26.630217,Asia
1,Afghanistan,2015,71.5,2.832290,33440000.0,17.7,9.384400,9.696866,30.953520,Asia
2,Afghanistan,2016,97.7,3.190059,38660000.0,20.2,8.605932,8.944815,28.075348,Asia
3,Afghanistan,2017,97.7,3.168652,39470000.0,19.5,9.311054,14.564168,36.517418,Asia
4,Afghanistan,2018,93.4,3.474043,38680000.0,18.3,10.191504,13.073680,46.492512,Asia

In [65]:
# Checking we no longer have missing values or duplicates before 
display(energy_df.isna().sum())
display(energy_df.duplicated().sum())

country             0
year                0
prct_access_elec    0
prct_renew_prod     0
renew_prod_kwh      0
prct_renew_cons     0
co2                 0
co2_luc             0
prim_ener_cons      0
region              0
dtype: int64

np.int64(0)

In [66]:
# Importing the dataset with the population and gdp data in order to merge:
gdp_pop = pd.read_csv("../data/clean/gdp_pop.csv")
display(gdp_pop.head())
display(gdp_pop.shape)

       country  year           GDP  population  gdp_per_cap
0  Afghanistan  2014  1.950046e+10  32792523.0   594.661805
1  Afghanistan  2015  1.869957e+10  33831764.0   552.722397
2  Afghanistan  2016  1.822435e+10  34700612.0   525.188137
3  Afghanistan  2017  1.903430e+10  35688935.0   533.339054
4  Afghanistan  2018  1.885632e+10  36743039.0   513.194331

(2321, 5)

In [67]:
# Correcting country names in order to match the countries in the energy_df based on the missing data i got after doing an initial merge:
gdp_name_map = {
    "Bolivia (Plurinational State of)": "Bolivia",
    "Brunei Darussalam": "Brunei",
    "Cabo Verde": "Cape Verde",
    "China (mainland)": "China",
    "Democratic Republic of the Congo": "Democratic Republic of Congo",
    "Côte d'Ivoire": "Cote d'Ivoire",
    "Kingdom of Eswatini": "Eswatini",
    "Iran, Islamic Republic of": "Iran",
    "Democratic People's Republic of Korea": "North Korea",
    "Republic of Korea": "South Korea",
    "Lao People's Democratic Republic": "Laos",
    "Micronesia (Federated States of)": "Micronesia (country)",
    "Republic of Moldova": "Moldova",
    "Republic of North Macedonia": "North Macedonia",
    "Russian Federation": "Russia",
    "Syrian Arab Republic": "Syria",
    "United Republic of Tanzania: Mainland": "Tanzania",
    "United Republic of Tanzania: Zanzibar": "Tanzania",
    "Timor-Leste": "East Timor",
    "Türkiye": "Turkey",
    "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
    "Venezuela (Bolivarian Republic of)": "Venezuela",
    "Viet Nam": "Vietnam",
    "State of Palestine": "Palestine"
}

gdp_pop["country"] = gdp_pop["country"].replace(gdp_name_map)

In [68]:
# Merging all the information we have on the co2 and energy consumption and production with the gdp and population dataset:
total = energy_df.merge(gdp_pop,on=["country", "year"],how="left")
display(total.head())
display(total.isna().sum())

,country,year,prct_access_elec,prct_renew_prod,renew_prod_kwh,prct_renew_cons,co2,co2_luc,prim_ener_cons,region,GDP,population,gdp_per_cap
0,Afghanistan,2014,89.5,2.772010,32440000.0,19.1,8.697668,8.776041,26.630217,Asia,1.950046e+10,32792523.0,594.661805
1,Afghanistan,2015,71.5,2.832290,33440000.0,17.7,9.384400,9.696866,30.953520,Asia,1.869957e+10,33831764.0,552.722397
2,Afghanistan,2016,97.7,3.190059,38660000.0,20.2,8.605932,8.944815,28.075348,Asia,1.822435e+10,34700612.0,525.188137
3,Afghanistan,2017,97.7,3.168652,39470000.0,19.5,9.311054,14.564168,36.517418,Asia,1.903430e+10,35688935.0,533.339054
4,Afghanistan,2018,93.4,3.474043,38680000.0,18.3,10.191504,13.073680,46.492512,Asia,1.885632e+10,36743039.0,513.194331

country             0
year                0
prct_access_elec    0
prct_renew_prod     0
renew_prod_kwh      0
prct_renew_cons     0
co2                 0
co2_luc             0
prim_ener_cons      0
region              0
GDP                 7
population          7
gdp_per_cap         7
dtype: int64

In [69]:
# Check for missing data in my new merged df:
missing_data = total.loc[total.isna().any(axis=1),'country'].unique()

display(missing_data)

<StringArray>
['Central African Republic']
Length: 1, dtype: str

In [70]:
# Import data for the country missing it on gdp and pop:
car_df=pd.read_csv("../data/raw/CAR_gdp_pop.csv")
car_df.head()

,Series Name,Series Code,Country Name,Country Code,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024],2025 [YR2025]
0,"Population, total",SP.POP.TOTL,Central African Republic,CAF,4.623182e+06,4.629320e+06,4.713663e+06,4.793511e+06,4.878657e+06,4.944703e+06,5.026628e+06,5.112100e+06,5.098039e+06,5.152421e+06,5.330690e+06,..
1,GDP (current US$),NY.GDP.MKTP.CD,Central African Republic,CAF,1.894813e+09,1.695826e+09,1.825018e+09,2.072350e+09,2.220979e+09,2.221301e+09,2.326721e+09,2.516498e+09,2.382619e+09,2.555492e+09,2.751494e+09,..
2,GDP per capita (current US$),NY.GDP.PCAP.CD,Central African Republic,CAF,4.098505e+02,3.663229e+02,3.871762e+02,4.323240e+02,4.552440e+02,4.492285e+02,4.628791e+02,4.922631e+02,4.673598e+02,4.959789e+02,5.161610e+02,..
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
# Cleaning df and preparing it to fill the missing data:
car_df.columns = [str(col).split('[')[0].strip().lower().replace(' ', '_')for col in car_df.columns]
car_df=car_df.drop(columns=['series_code','country_code'])
car_df = car_df.rename(columns={'country_name': 'country'})
car_df.columns

Index(['series_name', 'country', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020', '2021', '2022', '2023', '2024', '2025'],
      dtype='str')

In [72]:
# getting rid of unnecessary rows:
car_df=car_df.dropna()
car_df.isnull()

,series_name,country,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [73]:
# melt + pivot the data to match the destination format:
years=['2014','2015','2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024']
car_melt = pd.melt(car_df, id_vars=['country', 'series_name'], value_vars=years, var_name='year', value_name='value')
display(car_melt.head())

car_final=car_melt.pivot(index=['country','year'],columns='series_name',values='value').reset_index()
display(car_final.head())
car_final.dtypes

                    country                   series_name  year         value
0  Central African Republic             Population, total  2014  4.623182e+06
1  Central African Republic             GDP (current US$)  2014  1.894813e+09
2  Central African Republic  GDP per capita (current US$)  2014  4.098505e+02
3  Central African Republic             Population, total  2015  4.629320e+06
4  Central African Republic             GDP (current US$)  2015  1.695826e+09

series_name,country,year,GDP (current US$),GDP per capita (current US$),"Population, total"
0,Central African Republic,2014,1.894813e+09,409.850486,4623182.0
1,Central African Republic,2015,1.695826e+09,366.322854,4629320.0
2,Central African Republic,2016,1.825018e+09,387.176203,4713663.0
3,Central African Republic,2017,2.072350e+09,432.324026,4793511.0
4,Central African Republic,2018,2.220979e+09,455.243963,4878657.0

series_name
country                             str
year                                str
GDP (current US$)               float64
GDP per capita (current US$)    float64
Population, total               float64
dtype: object

In [74]:
# Match column names to the energy df and change year to integer:
car_final = car_final.rename(columns={'GDP (current US$)': 'GDP','GDP per capita (current US$)': 'gdp_per_cap','Population, total': 'population'})
display(car_final.head(12))

series_name,country,year,GDP,gdp_per_cap,population
0,Central African Republic,2014,1.894813e+09,409.850486,4623182.0
1,Central African Republic,2015,1.695826e+09,366.322854,4629320.0
2,Central African Republic,2016,1.825018e+09,387.176203,4713663.0
3,Central African Republic,2017,2.072350e+09,432.324026,4793511.0
4,Central African Republic,2018,2.220979e+09,455.243963,4878657.0
5,Central African Republic,2019,2.221301e+09,449.228468,4944703.0
6,Central African Republic,2020,2.326721e+09,462.879071,5026628.0
7,Central African Republic,2021,2.516498e+09,492.263143,5112100.0
8,Central African Republic,2022,2.382619e+09,467.359825,5098039.0
9,Central African Republic,2023,2.555492e+09,495.978897,5152421.0
10,Central African Republic,2024,2.751494e+09,516.161000,5330690.0

In [75]:
#Add the new data to our final dataset:
car_final['year']=car_final['year'].astype(int)

final_df = total.merge(car_final,on=['country', 'year'],how='left')
display(final_df.columns)

Index(['country', 'year', 'prct_access_elec', 'prct_renew_prod',
       'renew_prod_kwh', 'prct_renew_cons', 'co2', 'co2_luc', 'prim_ener_cons',
       'region', 'GDP_x', 'population_x', 'gdp_per_cap_x', 'GDP_y',
       'gdp_per_cap_y', 'population_y'],
      dtype='str')

In [76]:
#Filling missing data
final_df['GDP_x'] = final_df['GDP_x'].fillna(final_df['GDP_y'])
final_df['gdp_per_cap_x'] = final_df['gdp_per_cap_x'].fillna(final_df['gdp_per_cap_y'])
final_df['population_x'] = final_df['population_x'].fillna(final_df['population_y'])

final_df = final_df.drop(columns=['GDP_y', 'gdp_per_cap_y', 'population_y'])

final_df = final_df.rename(columns={'GDP_x': 'GDP','gdp_per_cap_x': 'gdp_per_cap','population_x': 'population'})

In [77]:
final_df.isna().sum()

country             0
year                0
prct_access_elec    0
prct_renew_prod     0
renew_prod_kwh      0
prct_renew_cons     0
co2                 0
co2_luc             0
prim_ener_cons      0
region              0
GDP                 0
population          0
gdp_per_cap         0
dtype: int64

In [78]:
# Save df to the output path defined in config, with reset index:
final_df.to_csv(cfg['output_data']['df3'], index=False)

print(f"File saved to: {cfg['output_data']['df3']}")

File saved to: ../data/clean/final_df.csv