In [1]:
import pandas as pd
import yaml



try:
    with open("../cfg.yaml", "r") as file:
        cfg=yaml.safe_load(file)
except:
    print("Yaml configuration file not found!")

In [2]:
gdp=pd.read_csv(cfg['input_data']['df2'])

In [3]:
gdp.head()

  Country/Area  Year Unit  GDP, at current prices - US Dollars
0  Afghanistan  2014  US$                         1.950046e+10
1  Afghanistan  2015  US$                         1.869957e+10
2  Afghanistan  2016  US$                         1.822435e+10
3  Afghanistan  2017  US$                         1.903430e+10
4  Afghanistan  2018  US$                         1.885632e+10

In [4]:
gdp.shape

(2332, 4)

In [5]:
gdp.isna().sum()

Country/Area                           0
Year                                   0
Unit                                   0
GDP, at current prices - US Dollars    0
dtype: int64

In [6]:
gdp.duplicated().sum()

np.int64(0)

In [7]:
# CRenaming columns for better undertanding and easier manipulation:
map_columns={'Country/Area':'country', 'Year':'year','GDP, at current prices - US Dollars':'GDP'}
gdp=gdp.rename(columns=map_columns)
gdp.columns

Index(['country', 'year', 'Unit', 'GDP'], dtype='str')

In [8]:
# Dropping unnecesary columns:
gdp=gdp.drop(columns=['Unit'])
gdp.columns

Index(['country', 'year', 'GDP'], dtype='str')

In [9]:
gdp.dtypes

country        str
year         int64
GDP        float64
dtype: object

In [10]:
gdp.head(20)

        country  year           GDP
0   Afghanistan  2014  1.950046e+10
1   Afghanistan  2015  1.869957e+10
2   Afghanistan  2016  1.822435e+10
3   Afghanistan  2017  1.903430e+10
4   Afghanistan  2018  1.885632e+10
5   Afghanistan  2019  1.937236e+10
6   Afghanistan  2020  1.998301e+10
7   Afghanistan  2021  1.516092e+10
8   Afghanistan  2022  1.417499e+10
9   Afghanistan  2023  1.633976e+10
10  Afghanistan  2024  1.828316e+10
11      Albania  2014  1.329632e+10
12      Albania  2015  1.147017e+10
13      Albania  2016  1.198867e+10
14      Albania  2017  1.325824e+10
15      Albania  2018  1.537951e+10
16      Albania  2019  1.558511e+10
17      Albania  2020  1.524146e+10
18      Albania  2021  1.803199e+10
19      Albania  2022  1.901725e+10

In [11]:
# Creating population df:
pop=pd.read_csv(cfg['input_data']['df3'])
pop.head()

  Country/Area  Year     Unit  Population
0  Afghanistan  2014  Persons    32792523
1  Afghanistan  2015  Persons    33831764
2  Afghanistan  2016  Persons    34700612
3  Afghanistan  2017  Persons    35688935
4  Afghanistan  2018  Persons    36743039

In [12]:
# Rename columns, drop unnecessary columns and check for duplicates or missing values:
map_popul={'Country/Area':'country', 'Year':'year','Population':'population'}
pop=pop.rename(columns=map_popul)
pop=pop.drop(columns=['Unit'])
display(pop.columns)
display(gdp.isna().sum())
display(gdp.duplicated().sum())

Index(['country', 'year', 'population'], dtype='str')

country    0
year       0
GDP        0
dtype: int64

np.int64(0)

In [13]:
display(gdp.shape)
display(pop.shape)
display(gdp.dtypes)
display(pop.dtypes)

(2332, 3)

(2321, 3)

country        str
year         int64
GDP        float64
dtype: object

country         str
year          int64
population    int64
dtype: object

In [14]:
# Join population and gdp in a new dataframe:
gdp_pop = pd.merge(
    left=gdp, 
    right=pop,
    how='left',
    left_on=['country', 'year'],
    right_on=['country', 'year'],)

display(gdp_pop.head())
display(gdp_pop.shape)
display(gdp_pop.dtypes)

       country  year           GDP  population
0  Afghanistan  2014  1.950046e+10  32792523.0
1  Afghanistan  2015  1.869957e+10  33831764.0
2  Afghanistan  2016  1.822435e+10  34700612.0
3  Afghanistan  2017  1.903430e+10  35688935.0
4  Afghanistan  2018  1.885632e+10  36743039.0

(2332, 4)

country           str
year            int64
GDP           float64
population    float64
dtype: object

In [15]:
# Handling missing values:
display(gdp_pop.duplicated().sum())
display(gdp_pop.isna().sum())
gdp_pop.loc[gdp_pop.isna().any(axis=1)]

np.int64(0)

country        0
year           0
GDP            0
population    11
dtype: int64

             country  year           GDP  population
2288  Western Africa  2014  8.841476e+11         NaN
2289  Western Africa  2015  8.034646e+11         NaN
2290  Western Africa  2016  7.215246e+11         NaN
2291  Western Africa  2017  7.222291e+11         NaN
2292  Western Africa  2018  8.310620e+11         NaN
2293  Western Africa  2019  9.353526e+11         NaN
2294  Western Africa  2020  8.768229e+11         NaN
2295  Western Africa  2021  9.248260e+11         NaN
2296  Western Africa  2022  9.598579e+11         NaN
2297  Western Africa  2023  8.347647e+11         NaN
2298  Western Africa  2024  6.231730e+11         NaN

In [16]:
# Drop rows with missing values as they are irrelevant to the study (they belong to a region classification not a country):
gdp_pop=gdp_pop.dropna()
display(gdp_pop.isna().sum())

country       0
year          0
GDP           0
population    0
dtype: int64

In [17]:
# create a new column for gdp per capita:
gdp_pop['gdp_per_cap']=gdp_pop['GDP'] / gdp_pop['population']
display(gdp_pop.head())

       country  year           GDP  population  gdp_per_cap
0  Afghanistan  2014  1.950046e+10  32792523.0   594.661805
1  Afghanistan  2015  1.869957e+10  33831764.0   552.722397
2  Afghanistan  2016  1.822435e+10  34700612.0   525.188137
3  Afghanistan  2017  1.903430e+10  35688935.0   533.339054
4  Afghanistan  2018  1.885632e+10  36743039.0   513.194331

In [18]:
# New data set:

renew=pd.read_csv(cfg['input_data']['df1'])

In [19]:
display(renew.head())
display(renew.info)

,Series Name,Series Code,Country Name,Country Code,2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024]
0,Access to electricity (% of population),EG.ELC.ACCS.ZS,Afghanistan,AFG,71.5,97.7,97.7,93.4,97.7,97.7,97.7,85.3,85.3,..
1,Access to electricity (% of population),EG.ELC.ACCS.ZS,Albania,ALB,100,99.9,99.9,100,100,100,100,100,100,..
2,Access to electricity (% of population),EG.ELC.ACCS.ZS,Algeria,DZA,99.4,99.4,99.5,99.6,99.5,99.7,99.8,100,100,..
3,Access to electricity (% of population),EG.ELC.ACCS.ZS,American Samoa,ASM,..,..,..,..,..,..,..,..,..,..
4,Access to electricity (% of population),EG.ELC.ACCS.ZS,Andorra,AND,100,100,100,100,100,100,100,100,100,..

<bound method DataFrame.info of                                           Series Name     Series Code  \
0             Access to electricity (% of population)  EG.ELC.ACCS.ZS
1             Access to electricity (% of population)  EG.ELC.ACCS.ZS
2             Access to electricity (% of population)  EG.ELC.ACCS.ZS
3             Access to electricity (% of population)  EG.ELC.ACCS.ZS
4             Access to electricity (% of population)  EG.ELC.ACCS.ZS
..                                                ...             ...
798                                               NaN             NaN
799                                               NaN             NaN
800                                               NaN             NaN
801  Data from database: World Development Indicators             NaN
802                          Last Updated: 04/08/2026             NaN

       Country Name Country Code 2015 [YR2015] 2016 [YR2016] 2017 [YR2017]  \
0       Afghanistan          AFG          71.5          97.7          97.7
1           Albania          ALB           100          99.9          99.9
2           Algeria          DZA          99.4          99.4          99.5
3    American Samoa          ASM            ..            ..            ..
4           Andorra          AND           100           100           100
..              ...          ...           ...           ...           ...
798             NaN          NaN           NaN           NaN           NaN
799             NaN          NaN           NaN           NaN           NaN
800             NaN          NaN           NaN           NaN           NaN
801             NaN          NaN           NaN           NaN           NaN
802             NaN          NaN           NaN           NaN           NaN

    2018 [YR2018] 2019 [YR2019] 2020 [YR2020] 2021 [YR2021] 2022 [YR2022]  \
0            93.4          97.7          97.7          97.7          85.3
1             100           100           100           100           100
2            99.6          99.5          99.7          99.8           100
3              ..            ..            ..            ..            ..
4             100           100           100           100           100
..            ...           ...           ...           ...           ...
798           NaN           NaN           NaN           NaN           NaN
799           NaN           NaN           NaN           NaN           NaN
800           NaN           NaN           NaN           NaN           NaN
801           NaN           NaN           NaN           NaN           NaN
802           NaN           NaN           NaN           NaN           NaN

    2023 [YR2023] 2024 [YR2024]
0            85.3            ..
1             100            ..
2             100            ..
3              ..            ..
4             100            ..
..            ...           ...
798           NaN           NaN
799           NaN           NaN
800           NaN           NaN
801           NaN           NaN
802           NaN           NaN

[803 rows x 14 columns]>

In [20]:
renew.columns

Index(['Series Name', 'Series Code', 'Country Name', 'Country Code',
       '2015 [YR2015]', '2016 [YR2016]', '2017 [YR2017]', '2018 [YR2018]',
       '2019 [YR2019]', '2020 [YR2020]', '2021 [YR2021]', '2022 [YR2022]',
       '2023 [YR2023]', '2024 [YR2024]'],
      dtype='str')

In [21]:
def clean_years(col):
    return col.split('[')[0].strip()

renew.columns=[clean_years(col) for col in renew.columns]
renew.columns
years=['2015','2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024']

In [22]:
renew=renew.drop(columns=['Series Code','Country Code'])
renew.columns

Index(['Series Name', 'Country Name', '2015', '2016', '2017', '2018', '2019',
       '2020', '2021', '2022', '2023', '2024'],
      dtype='str')

In [23]:
def rename_column(col):
    return col.lower().replace(' ','_').strip()

renew.columns=[rename_column(col) for col in renew.columns]
renew.columns

Index(['series_name', 'country_name', '2015', '2016', '2017', '2018', '2019',
       '2020', '2021', '2022', '2023', '2024'],
      dtype='str')

In [24]:
renew.isna().sum()

series_name     3
country_name    5
2015            5
2016            5
2017            5
2018            5
2019            5
2020            5
2021            5
2022            5
2023            5
2024            5
dtype: int64

In [25]:
renew.duplicated().sum()

np.int64(2)

In [26]:
renew.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
798    False
799     True
800     True
801    False
802    False
Length: 803, dtype: bool

In [27]:
renew.loc[[798,799]]

    series_name country_name 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024
798         NaN          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
799         NaN          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

In [28]:
renew = renew.drop(index=[798,799])
renew.duplicated().sum()

np.int64(0)

In [29]:
renew.isna().sum()

series_name     1
country_name    3
2015            3
2016            3
2017            3
2018            3
2019            3
2020            3
2021            3
2022            3
2023            3
2024            3
dtype: int64

In [30]:
renew.loc[renew.isna().any(axis=1)]

,series_name,country_name,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
801,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
802,Last Updated: 04/08/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
renew=renew.dropna()
display(renew.isna().sum())

series_name     0
country_name    0
2015            0
2016            0
2017            0
2018            0
2019            0
2020            0
2021            0
2022            0
2023            0
2024            0
dtype: int64

In [32]:
renew_melt = pd.melt(renew, id_vars=['country_name', 'series_name'], value_vars=years, var_name='year', value_name='value')
display(renew_melt.head())

     country_name                              series_name  year value
0     Afghanistan  Access to electricity (% of population)  2015  71.5
1         Albania  Access to electricity (% of population)  2015   100
2         Algeria  Access to electricity (% of population)  2015  99.4
3  American Samoa  Access to electricity (% of population)  2015    ..
4         Andorra  Access to electricity (% of population)  2015   100

In [33]:
renew_df=renew_melt.pivot(index=['country_name','year'],columns='series_name',values='value').reset_index()
renew_df.head()

series_name,country_name,year,Access to electricity (% of population),"Electricity production from renewable sources, excluding hydroelectric (% of total)",Renewable energy consumption (% of total final energy consumption)
0,Afghanistan,2015,71.5,2.83229014034404,17.7
1,Afghanistan,2016,97.7,3.19005850365957,20.2
2,Afghanistan,2017,97.7,3.16865225907967,19.5
3,Afghanistan,2018,93.4,3.47404347045087,18.3
4,Afghanistan,2019,97.7,3.82453122312059,18.9

In [34]:
renew_df.duplicated().sum()

np.int64(0)

In [35]:
renew_df.isna().sum()

series_name
country_name                                                                           0
year                                                                                   0
Access to electricity (% of population)                                                0
Electricity production from renewable sources, excluding hydroelectric (% of total)    0
Renewable energy consumption (% of total final energy consumption)                     0
dtype: int64

In [36]:
# renaming new columns to practical names:
map_renew={'country_name':'country','Access to electricity (% of population)':'prct_access_elec','Electricity production from renewable sources, excluding hydroelectric (% of total)':'prct_renew_prod','Renewable energy consumption (% of total final energy consumption)':'prct_renew_cons'}
renew_df=renew_df.rename(columns=map_renew)
renew_df.columns

Index(['country', 'year', 'prct_access_elec', 'prct_renew_prod',
       'prct_renew_cons'],
      dtype='str', name='series_name')

In [37]:
# Creating csv files with clean data from both final dataframes **DO NOT RUN**:
# renew_df.to_csv("renew.csv", index=False)
# gdp_pop.to_csv("gdp_pop.csv", index=False)